name: CI/CD Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    pr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install dependencies
              run: yarn install

            - name: Run tests
              run: yarn test

            - name: Build the project
              run: yarn build

            - name: Authenticate with GitHub
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: github.com

            - name: Configure Git
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            - name: Fetch main branch
              run: |
                  git remote set-url origin git@github.com:Jme797/prettier-plugin-remove-unused-imports.git
                  git fetch origin main

            - name: Merge main into PR branch
              run: |
                  git checkout ${{ github.event.pull_request.head.ref }}
                  git merge origin/main

            - name: Increment version
              run: |
                  npm version patch -m "ci: bump version to %s"

            - name: Push version bump
              run: |
                  git push origin HEAD:${{ github.event.pull_request.head.ref }}

    deploy:
        if: "github.event.head_commit.message == 'ci: bump version'"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install dependencies
              run: yarn install

            - name: Run tests
              run: yarn test

            - name: Build the project
              run: yarn build

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
